sport = {'dota': {'2020-08-06 21:00:00: thunder predator - midas club': [{'midas club will win': ['5.66(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'], 'thunder predator will win': ['1.12(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)']}],
          '2020-08-06 21:15:00: omegalil - voldemort': [{'1-st map: omegalil handicap -10.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         '1-st map: total kills over 49.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         '1-st map: total kills under 49.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         '1-st map: voldemort handicap +10.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         'omegalil handicap -1.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         'omegalil will win': ['1.22(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         'total maps over 2.5': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         'total maps under 2.5': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         'voldemort handicap +1.5 maps': ['1.98(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                         'voldemort will win': ['4.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)']}],
          '2020-08-07 00:00:00: infamous - omega': [{'infamous will win': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'], 'omega will win': ['3.45(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)']}],
          '2020-08-07 05:30:00: future.club - hot pot brother': [{'future.club will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)'],
                                                                  'hot pot brother will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)']}],
          '2020-08-07 06:00:00: execration - black': [{'black handicap +1.5 maps': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                       'black will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                       'execration handicap -1.5 maps': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                       'execration will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                       'total maps over 2.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                       'total maps under 2.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)']}],
          '2020-08-07 07:30:00: neon  - adroit': [{'1-st map: adroit handicap +4.5 kills': ['1.67(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   '1-st map: neon  handicap -4.5 kills': ['2.10(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   '1-st map: total kills over 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   '1-st map: total kills under 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   'adroit handicap +1.5 maps': ['1.28(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   'adroit will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   'neon  handicap -1.5 maps': ['3.45(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   'neon  will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   'total maps over 2.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                   'total maps under 2.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)']}],
          '2020-08-07 08:30:00: wolf - sunrise': [{'sunrise will win': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)'], 'wolf will win': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)']}],
          "2020-08-07 11:00:00: c's better - nobkb": [{"c's better will win": ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-oceanic-league)'],
                                                       'draw will win': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-oceanic-league)'],
                                                       'nobkb will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-oceanic-league)']}],
          '2020-08-07 11:30:00: wolf - rockets': [{'rockets will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)'], 'wolf will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-asian-gold-occupation)']}],
          '2020-08-07 12:00:00: ig vitality - cellular game': [{'cellular game handicap +1.5 maps': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                                'cellular game will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                                'ig vitality handicap -1.5 maps': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                                'ig vitality will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                                'total maps over 2.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)'],
                                                                'total maps under 2.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-moon-studio-asian-league)']}],
          '2020-08-07 13:00:00: spag and sons - adio chula': [{'adio chula will win': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-oceanic-league)'],
                                                               'draw will win': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-oceanic-league)'],
                                                               'spag and sons will win': ['5.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-oceanic-league)']}],
          '2020-08-07 14:00:00: 5comrades - motaci': [{'1-st map: 5comrades handicap -11.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                       '1-st map: motaci handicap +11.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                       '5comrades will win': ['1.20(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                       'motaci will win': ['4.20(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)']}],
          '2020-08-07 15:15:00: extremum - evil corporation': [{'1-st map: evil corporation handicap +8.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                                '1-st map: extremum handicap -8.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                                'evil corporation will win': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                                                'extremum will win': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)']}],
          '2020-08-07 17:45:00: b8 - tempo': [{'1-st map: b8 handicap -6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               '1-st map: tempo handicap +6.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               '1-st map: total kills over 47.5': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               '1-st map: total kills under 47.5': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               'b8 handicap -1.5 maps': ['2.11(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               'b8 will win': ['1.35(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               'tempo handicap +1.5 maps': ['1.68(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               'tempo will win': ['3.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               'total maps over 2.5': ['2.20(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)'],
                                               'total maps under 2.5': ['1.62(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-eu-qualifier)']}],
          '2020-08-07 23:00:00: spirits - egoboys': [{'draw will win': ['2.13(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)'],
                                                      'egoboys will win': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)'],
                                                      'spirits will win': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)']}],
          '2020-08-08 01:00:00: sandblood - vicious': [{'draw will win': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)'],
                                                        'sandblood will win': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)'],
                                                        'vicious will win': ['4.21(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-the-great-american-division-2)']}],
          '2020-08-08 07:30:00: blaze - demonster': [{'1-st map: blaze handicap -7.5 kills': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      '1-st map: demonster handicap +7.5 kills': ['1.84(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      '1-st map: total kills over 45.5': ['1.90(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      '1-st map: total kills under 45.5': ['1.84(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      'blaze handicap -1.5 maps': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      'blaze will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      'demonster handicap +1.5 maps': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      'demonster will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      'total maps over 2.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)'],
                                                      'total maps under 2.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-omega-league-as-divine-division)']}],
          '2020-08-08 20:00:00: cr4zy - thunder predator': [{'1-st map: cr4zy handicap +4.5 kills': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: cr4zy handicap -3.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: cr4zy handicap -4.5 kills': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: thunder predator handicap +3.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: thunder predator handicap +4.5 kills': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: thunder predator handicap -4.5 kills': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: total kills over 49.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: total kills over 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: total kills over 53.5': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: total kills under 49.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: total kills under 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '1-st map: total kills under 53.5': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: cr4zy handicap +4.5 kills': ['1.57(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: cr4zy handicap -3.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: cr4zy handicap -4.5 kills': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: thunder predator handicap +3.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: thunder predator handicap +4.5 kills': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: thunder predator handicap -4.5 kills': ['2.31(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: total kills over 49.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: total kills over 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: total kills over 53.5': ['2.05(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: total kills under 49.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: total kills under 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             '2-nd map: total kills under 53.5': ['1.72(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             'cr4zy handicap -1.5 maps': ['3.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             'cr4zy will win': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             'thunder predator handicap +1.5 maps': ['1.31(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             'thunder predator will win': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             'total maps over 2.5': ['2.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                             'total maps under 2.5': ['1.76(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)']}],
          '2020-08-08 21:00:00: brasil - pacific': [{'brasil will win': ['1.22(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'], 'pacific will win': ['4.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)']}],
          '2020-08-08 23:00:00: business associates - infamous': [{'1-st map: business associates handicap -4.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: business associates handicap -5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: business associates handicap -6.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: infamous handicap +4.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: infamous handicap +5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: infamous handicap +6.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: total kills over 49.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: total kills over 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: total kills over 53.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: total kills under 49.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: total kills under 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '1-st map: total kills under 53.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: business associates handicap -4.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: business associates handicap -5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: business associates handicap -6.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: infamous handicap +4.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: infamous handicap +5.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: infamous handicap +6.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: total kills over 49.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: total kills over 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: total kills over 53.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: total kills under 49.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: total kills under 51.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   '2-nd map: total kills under 53.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   'business associates handicap -1.5 maps': ['2.42(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   'business associates will win': ['1.45(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   'infamous handicap +1.5 maps': ['1.52(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   'infamous will win': ['2.62(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   'total maps over 2.5': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                   'total maps under 2.5': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)']}],
          '2020-08-09 00:00:00: egoboys - unknown': [{'egoboys will win': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)'], 'unknown will win': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-movistar-lpg)']}],
          '2020-08-09 23:00:00: quincy crew - 4 zoomers': [{'1-st map: 4 zoomers handicap +12.5 kills': ['1.98(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: 4 zoomers handicap +13.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: 4 zoomers handicap +14.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: quincy crew handicap -12.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: quincy crew handicap -13.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: quincy crew handicap -14.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: total kills over 48.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: total kills over 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: total kills over 52.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: total kills under 48.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: total kills under 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '1-st map: total kills under 52.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: 4 zoomers handicap +12.5 kills': ['1.98(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: 4 zoomers handicap +13.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: 4 zoomers handicap +14.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: quincy crew handicap -12.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: quincy crew handicap -13.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: quincy crew handicap -14.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: total kills over 48.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: total kills over 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: total kills over 52.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: total kills under 48.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: total kills under 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '2-nd map: total kills under 52.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '4 zoomers handicap +1.5 maps': ['2.16(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            '4 zoomers will win': ['4.50(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            'quincy crew handicap -1.5 maps': ['1.65(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            'quincy crew will win': ['1.18(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            'total maps over 2.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                            'total maps under 2.5': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)']}],
          '2020-08-11 20:00:00: cr4zy - infamous': [{'1-st map: cr4zy handicap -10.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: cr4zy handicap -11.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: cr4zy handicap -9.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: infamous handicap +10.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: infamous handicap +11.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: infamous handicap +9.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: total kills over 48.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: total kills over 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: total kills over 52.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: total kills under 48.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: total kills under 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '1-st map: total kills under 52.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: cr4zy handicap -10.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: cr4zy handicap -11.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: cr4zy handicap -9.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: infamous handicap +10.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: infamous handicap +11.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: infamous handicap +9.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: total kills over 48.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: total kills over 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: total kills over 52.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: total kills under 48.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: total kills under 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     '2-nd map: total kills under 52.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     'cr4zy handicap -1.5 maps': ['1.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     'cr4zy will win': ['1.15(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     'infamous handicap +1.5 maps': ['2.35(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     'infamous will win': ['5.00(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     'total maps over 2.5': ['2.55(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                     'total maps under 2.5': ['1.47(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)']}],
          '2020-08-11 23:00:00: beastcoast - 4 zoomers': [{'1-st map: 4 zoomers handicap -5.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: 4 zoomers handicap -6.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: 4 zoomers handicap -7.5 kills': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: beastcoast handicap +5.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: beastcoast handicap +6.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: beastcoast handicap +7.5 kills': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: total kills over 48.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: total kills over 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: total kills over 52.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: total kills under 48.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: total kills under 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '1-st map: total kills under 52.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: 4 zoomers handicap -5.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: 4 zoomers handicap -6.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: 4 zoomers handicap -7.5 kills': ['2.01(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: beastcoast handicap +5.5 kills': ['1.92(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: beastcoast handicap +6.5 kills': ['1.82(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: beastcoast handicap +7.5 kills': ['1.75(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: total kills over 48.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: total kills over 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: total kills over 52.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: total kills under 48.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: total kills under 50.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '2-nd map: total kills under 52.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '4 zoomers handicap -1.5 maps': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           '4 zoomers will win': ['1.40(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           'beastcoast handicap +1.5 maps': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           'beastcoast will win': ['2.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           'total maps over 2.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                           'total maps under 2.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)']}],
          '2020-08-12 23:00:00: business associates - thunder predator': [{'1-st map: business associates handicap +10.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: business associates handicap +11.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: business associates handicap +12.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: thunder predator handicap -10.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: thunder predator handicap -11.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: thunder predator handicap -12.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: total kills over 46.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: total kills over 48.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: total kills over 50.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: total kills under 46.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: total kills under 48.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '1-st map: total kills under 50.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: business associates handicap +10.5 kills': ['1.95(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: business associates handicap +11.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: business associates handicap +12.5 kills': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: thunder predator handicap -10.5 kills': ['1.80(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: thunder predator handicap -11.5 kills': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: thunder predator handicap -12.5 kills': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: total kills over 46.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: total kills over 48.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: total kills over 50.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: total kills under 46.5': ['2.08(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: total kills under 48.5': ['1.87(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           '2-nd map: total kills under 50.5': ['1.70(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           'business associates handicap +1.5 maps': ['1.77(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           'business associates will win': ['3.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           'thunder predator handicap -1.5 maps': ['1.97(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           'thunder predator will win': ['1.30(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           'total maps over 2.5': ['2.25(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)'],
                                                                           'total maps under 2.5': ['1.60(parimatch - https://www.parimatch.com/en/sport/kibersport/dota-2-esl-one-thailand-am)']}]}}
